### ISSUE TITLE
Unable to create terminal

### ISSUE THREAD

**Issue by mrfloppi** [BenWildeman/vscode-tabulous#15]
<img width="1136" alt="Bildschirmfoto 2019-11-09 um 02 42 03" src="https://user-images.githubusercontent.com/2563292/68520741-97030c80-029a-11ea-95b7-98edb5a2ab73.png">

@BenWildeman 
I use and love your plugin on my macbook. Installed it today on my iMac and no matter how often I install/uninstall it it's not doing anything.

If I trigger `>Tabulous: Create terminal `it just gives an error:
`Unable to create terminal`

If I instead just enter:
`term` hit spacebar and choose the option "Create New Integrated Terminal"
a terminal get's created

That's really weird.

**Comment by mrfloppi** [comment]
To verify, that it's not the maschine itself or some weird configuration problem, I've now installed VSCode freshly on another mac altogether with Tabulous, and also there the same error appears.

Seems like the plugin is broken at the moment.

**Comment by BenWildeman** [comment]
I have a fix already for this I need to publish. I assume you don't have a workspace which is why it won't create the terminal

**Comment by BenWildeman** [comment]
@mrfloppi fix published, please could you confirm that it works now?

**Comment by jryden** [comment]
@BenWildeman Does not work on Xubuntu 19.10 with or without WorkSpace - same error as above.

**Comment by mrfloppi** [comment]
@BenWildeman Thanks for the quick response! Just had a check after updating Tabulous. Sadly the error remains like described initially no matter if I have a workspace or not.

**Comment by BenWildeman** [comment]
I should be able to replicate myself. I have seen issues on macOS too so there's quite a bit broken

**Comment by BenWildeman** [comment]
Published a fix. Please can someone confirm the issue has been fixed for real this time

**Comment by jryden** [comment]
@BenWildeman Works for me. Thanks!

**Comment by BenWildeman** [comment]
@mrfloppi I've published 1.0.3 today which covers the issue you faced. I didn't realise in the screenshot that you didn't have a folder or workspace open

**Comment by mrfloppi** [comment]
Great, thanks a lot for the update. Cheers @BenWildeman 🎉
