### ISSUE TITLE
Default terminals aren't opening automatically when I open the project.

### ISSUE THREAD

**Issue by joisadler** [BenWildeman/vscode-tabulous#16]
Hi! After upgrade to version 1.0.1 (from 0.5.0), when I open my project, my default tabs do not appear in the status bar. The same thing in version 1.0.0. After downgrading to version 0.5.0 everything again works perfectly. Is it possible to fix this problem?
Here is my `settings.json`:
```json
{
  "tabulous.defaultTerminals": [{
    "name": "NPM run dev",
    "directory": "./",
    "command": "npm run dev",
    "executeCommand": true
  }, {
    "name": "Working Section",
    "directory": "./"
  }]
}
```

**Comment by BenWildeman** [comment]
pretty sure this is linked to #15 and I have published a fix for this. Please could you check to see if this issue is now resolved for you? Apologies for the inconvenience

**Comment by joisadler** [comment]
Everything works well. Thanks!
