### ISSUE TITLE
Opening a workspace list the terminal icons twice

### ISSUE THREAD

**Issue by kazelone** [BenWildeman/vscode-tabulous#18]
Bottom bar show twice the set of terminals icons, all 2nd one appear "selected" and switching of terminal by clicking on the icon is broken.

**Comment by kazelone** [comment]
There seems to be race-condition going on where sometime onDidOpenTerminal trigger before `loadTerminals()` do `common.terminals.set(...)`.
I have a PR that at least fix it, but it's most likely not the cleanest of way to fix it.

**Comment by BenWildeman** [comment]
have you experienced this since? I haven't for a while now
