### ISSUE TITLE
Release fix for terminal opened outside of tabulous

### ISSUE THREAD

**Issue by kazelone** [BenWildeman/vscode-tabulous#4]
The [lastest commit you made in 2018 that fix terminal not opened by tabulous](https://github.com/ray58750034/vscode-tabulous/commit/684386eff7608890c7c27bc1c82681f890ea9c1c) works pretty well. However, it haven't been released and pushed to the marketplace (latest version is 0.4.0, just before this commit).
Any reason this isn't published?

**Comment by BenWildeman** [comment]
I haven't personally needed it since making that commit. I'll do another release soon to include that functionality

**Comment by BenWildeman** [comment]
Done a release now. also included the terminal tracking PR I had sat waiting for 10 months
